### PR TITLE
v1.0 rewrite

### PR DESCRIPTION
**Pull request by aleclarson**
Hey, I liked the design of this library, so I "rewrote" it for some sweet gains. Any feedback is welcome!

### API changes

- Replaced `bindAll` with `"all"` key name (eg: `charm.bind('all', () => {})`)
- Improved `unbind` method
  - `charm.unbind(key)` removes all keydown handlers for `key`
  - `charm.unbind(key, 'keyup')` removes all keyup handlers for `key`
- Improved `getKey` method
  - Returns `null` for unsupported keys, so you can do `key == null` instead of `!key.startsWith('unknown')`
- Improved type definitions
  - Auto-completion for key names (when calling `bind` or `unbind`)
  - Renamed types from `Keycharm` to `KeyCharm`
- Renamed `destroy` method to `dispose`
- 🐛 Avoid calling `event.preventDefault` if no handlers exist for that key

### Other changes

- 852B min+gzip (15.3% decrease)
- Added `.mjs` bundle (mainly for [`vite`](https://github.com/vitejs/vite) support)
- Separated the CommonJS (`main`) and UMD (`unpkg`/`jsdelivr`) bundles
- Modern syntax, rewritten in TypeScript
- Added [`prettier`](https://github.com/prettier/prettier) for care-free formatting
- Added [`tsup`](https://github.com/egoist/tsup) for easy bundling

### CODE REVIEW

**Comment by AlexDM0** [comment]
Hi Alec,

Thanks for the interest in this little library! Even though it's a small library, I'm hesitant to change the API, mostly for the purpose of changing the API. While the code is old, it is functional as-is, and it's integrated in a few packages. This change would require the current users to update their code without any specific gain for them spare the smaller size.

There is a lot happening in this pull request, and I cant merge it like this. Maybe this is better suited as a fork?

I've looked at the code you've committed, even though I won't be using it, here's a review:

- I don't particularly like the each method, it seems an unnecessary diversion from vanilla. I prefer to keep my implementations as close to vanilla as possible to make it more recognisable for other developers.

- everything is jammed into a single file. If I'd rewrite this, I'd probably make a file with a class containing keycharm and it's member functions. This would be typed and used to generate the interface. I'd have an index that exports the required modules and I'd have a definitions file that contains the types and interfaces.

- you didn't update the docs.

- I don't see the need for tsup, can you argue why you used this?

- I don't see the mjs bundle in your commit, even though it's part of your listed changes.

- I like the separate formats as output.

Thanks for the effort nonetheless!

**Comment by aleclarson** [comment]
Hey Alex, thanks for the feedback! You could've easily ignored my PR altogether. :)

> This change would require the current users to update their code

I disagree. Since it would be a new major version, users would need to opt-in. We would document the breaking changes for easier migrating.

> Maybe this is better suited as a fork?

The breaking changes aren't bad enough to warrant that, IMO. The API is 99% the same. I see this PR as a logical evolution, not a derivative work.

> I don't particularly like the each method, it seems an unnecessary diversion from vanilla. I prefer to keep my implementations as close to vanilla as possible to make it more recognisable for other developers.

This was done for minification purposes. It's easy to option+click the callsite to see the implementation. I don't see it as a barrier to contribution at all.

> everything is jammed into a single file. If I'd rewrite this, I'd probably make a file with a class containing keycharm and it's member functions. This would be typed and used to generate the interface. 

I don't see the point in declaring a class for a singleton object. That would introduce `this` everywhere (bad for minification) for no perceivable gain. 

> I'd have an index that exports the required modules and I'd have a definitions file that contains the types and interfaces.

It's a single-purpose module with only 183 lines (including whitespace, excluding giant type union at bottom), which doesn't warrant module fragmentation, IMO. Regardless, if you feel strongly about this point, we could do it.

> you didn't update the docs.

Wanted to get your feedback first. :)

> I don't see the need for tsup, can you argue why you used this?

`tsup` makes it super easy to generate all the different bundles without managing your own Rollup configuration and all the various dev dependencies. Highly recommended!

> I don't see the mjs bundle in your commit, even though it's part of your listed changes.

It's generated by `tsup` into `./dist/` which is ignored by git. This means we're not forced to maintain both a CommonJS version and a ESM version of the same code! 🎉 

> I like the separate formats as output.

`tsup` gets all the credit there ;)

**Comment by AlexDM0** [comment]
What would be the main goal of this refactor? There are a few changes (summarised):
1 - minor API changes, most of which are personal preference
2 - prettierrc for formatting
3 - better typing
4 - smaller package
5 - builder
6 - source built in typescript

I propose we'd leave the API as-is, and first focus on the behind the scenes part. An API change can be a different pull request. We can make an issue discussing a new api after the initial refactor has been finalized.

> This was done for minification purposes. It's easy to option+click the callsite to see the implementation. I don't see it as a barrier to contribution at all.
Sure, minification isn't usually at the top of my list, readability is. Yes, you can option-click it, but that's not the point. This method is also in jquery, so people using that may conclude jquery is used. It's mental overhead and even though this is just one thing, the whole point it just to avoid this behaviour in general. If the main focus of this refactor is package size, then that's a different story.

>I don't see the point in declaring a class for a singleton object. That would introduce this everywhere (bad for minification) for no perceivable gain.
True, I suppose I just like the class format to have clear encapsulation. As I pointed out before, my main focus isn't minification. The this is now implied in the closure, which works, but it is less obvious.

> It's a single-purpose module with only 183 lines (including whitespace, excluding giant type union at bottom), which doesn't warrant module fragmentation, IMO. Regardless, if you feel strongly about this point, we could do it.
If the point of this refactor is to modernize the library, then why not make it a proper project structure?

I'll have to read up on tsup :)

Keep in mind this library has been written a long long time ago, so most of the points I'm trying to make here are not necessarily shown in this project :)

Small note: the bindAll is only meant for development, not for usage in the library. That is why there is no unbind('all') and that is why it is a different function. To make explicitly clear this is not meant to be used in the same way as binding keys.

**Comment by aleclarson** [comment]
I apologize for being too eager to mold this into my own taste, instead of discussing the changes with you beforehand. I think our goals/rationale are too at odds to continue further, and I feel bad for wasting your time with this review. Not to mention, I've a better idea for the design of a key binding library, so I probably won't even use these changes I made. 😅 

I'm gonna close this now. Have a good one!

**Comment by AlexDM0** [comment]
Hi Alec, I appreciate the enthusiasm and best of luck on your new lib!

Cheers

________________________________

**Pull request closed without merging**
