### PR TITLE
Rename LICENSE-MIT to LICENSE for spec compliance

### PR DESCRIPTION
**Pull request by evictor**

### CODE REVIEW

**Comment by mojoaxel** [comment]
:warning: This project has two licenses.

**Comment by evictor** [comment]
Strange

**Comment by mojoaxel** [comment]
Maybe you can update your PR to fix the two license files like so:
https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project

**Comment by evictor** [comment]
I see you're fixing it elsewhere... will close this PR

**Pull request closed without merging**
